<?xml version="1.0" encoding="utf-8"?>
<robot name="glr_description" xmlns:xacro="http://ros.org/wiki/xacro">
  
  <!-- Wheel properties -->
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_width" value="0.08" />
  <xacro:property name="caster_radius" value="0.05" />
  
  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w d h">
    <inertia ixx="${1*(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${1*(m/12) * (w*w + d*d)}" iyz="0.0" izz="${1*(m/12) * (w*w + h*h)}"/>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia ixx="${1*(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${1*(2/5) * m * (r*r)}" iyz="0.0" izz="${1*(2/5) * m * (r*r)}"/>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <!-- <origin xyz="0 0 0" rpy="${pi/2} 0 0" /> -->
      <mass value="${m}"/>
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0" iyy="${m*(3*r*r+h*h)/12}" iyz = "0" izz="${m*r*r/2}" /> 
      <!-- <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/> -->
    </inertial>
  </xacro:macro>

  <!--Robot description  -->
  <link name="base_link"/>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Tugger -->
  <link name="chassibigga">
    <origin
        xyz="0 0 0"
        rpy="0 0 0" />
    <inertial>
      <origin
        xyz="0 0 0.155"
        rpy="0 0 0" />
      <mass
        value="555.02" />
      <xacro:box_inertia m="555.02" w="0.5" d="0.7" h="0.31"/>
    </inertial>
    <visual>
      <origin
        xyz="0 0 0.155"
        rpy="0 0 0" />
      <geometry>
          <box size="0.50 0.70 0.31"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.64706 0.61961 0.58824 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0.155"
        rpy="0 0 0" />
      <geometry>
          <box size="0.50 0.70 0.31"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="chassibigga">
    <material>Gazebo/Orange</material>
  </gazebo>

  <joint name="base_chassi_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassibigga"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>
  
  <!-- Left Traction Wheel -->
  <link name="left_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="12"/>
      <xacro:sphere_inertia m="12" r="${wheel_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="wheel_material">
        <color rgba="0.29804 0.29804 0.29804 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <joint name="left_wheel_joint" type="continuous">
    <origin xyz="0.25 0 0" rpy="0 0 0"/>
    <parent link="chassibigga"/>
    <child link="left_wheel"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Right Traction Wheel -->
  <link name="right_wheel">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="12"/>
      <xacro:sphere_inertia m="12" r="${wheel_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="wheel_material">
        <color rgba="0.29804 0.29804 0.29804 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <joint name="right_wheel_joint" type="continuous">
    <origin xyz="-0.25 0 0" rpy="0 0 0"/>
    <parent link="chassibigga"/>
    <child link="right_wheel"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>
  
  <!-- Front Left Caster Mount -->
  <link name="front_left_caster_mount">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="front_left_caster_steering_joint" type="continuous">
    <origin xyz="0.2 -0.3 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
    <parent link="chassibigga"/>
    <child link="front_left_caster_mount"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- Front Left Caster Wheel -->
  <link name="front_left_caster">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="caster_material">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="front_left_caster">
    <material>Gazebo/Grey</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

  <joint name="front_left_caster_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="front_left_caster_mount"/>
    <child link="front_left_caster"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- Front Right Caster Mount -->
  <link name="front_right_caster_mount">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="front_right_caster_steering_joint" type="continuous">
    <origin xyz="-0.2 -0.3 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
    <parent link="chassibigga"/>
    <child link="front_right_caster_mount"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- Front Right Caster Wheel -->
  <link name="front_right_caster">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="caster_material">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="front_right_caster">
    <material>Gazebo/Grey</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

  <joint name="front_right_caster_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="front_right_caster_mount"/>
    <child link="front_right_caster"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- ============================================ -->
  <!-- CASTER WHEELS (Back - 2 wheels) -->
  <!-- ============================================ -->
  
  <!-- Back Left Caster Mount -->
  <link name="back_left_caster_mount">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="back_left_caster_steering_joint" type="continuous">
    <origin xyz="0.2 0.3 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
    <parent link="chassibigga"/>
    <child link="back_left_caster_mount"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- Back Left Caster Wheel -->
  <link name="back_left_caster">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="caster_material">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="back_left_caster">
    <material>Gazebo/Grey</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

  <joint name="back_left_caster_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="back_left_caster_mount"/>
    <child link="back_left_caster"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- Back Right Caster Mount -->
  <link name="back_right_caster_mount">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="back_right_caster_steering_joint" type="continuous">
    <origin xyz="-0.2 0.3 ${-wheel_radius + caster_radius}" rpy="0 0 0"/>
    <parent link="chassibigga"/>
    <child link="back_right_caster_mount"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- Back Right Caster Wheel -->
  <link name="back_right_caster">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <xacro:sphere_inertia m="0.5" r="${caster_radius}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="caster_material">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="back_right_caster">
    <material>Gazebo/Grey</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

  <joint name="back_right_caster_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="back_right_caster_mount"/>
    <child link="back_right_caster"/>
    <axis xyz="1 0 0"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <!-- ============================================ -->
  <!-- DIFFERENTIAL DRIVE PLUGIN -->
  <!-- ============================================ -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <remapping>cmd_vel:=cmd_vel</remapping>
        <remapping>odom:=odom</remapping>
      </ros>

      <update_rate>100.0</update_rate>

      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>

      <wheel_separation>0.5</wheel_separation>
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>

      <max_wheel_torque>200</max_wheel_torque>
      <max_wheel_acceleration>10.0</max_wheel_acceleration>

      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <!-- ============================================ -->
  <!-- TUGGER-TRAILER CONNECTION -->
  <!-- ============================================ -->
  
  <!-- Hitch point at the back of tugger (old base_link position) -->
  <link name="hitch_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
      <material name="hitch_material">
        <color rgba="0.3 0.3 0.3 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="hitch_link">
    <material>Gazebo/DarkGrey</material>
  </gazebo>

  <joint name="hitch_joint" type="fixed">
    <origin xyz="0 0.35 0.14260" rpy="0 0 0"/>
    <parent link="chassibigga"/>
    <child link="hitch_link"/>
  </joint>

  <joint name="eixochassibigga"
    type="revolute">
    <origin
      xyz="0 0 0"
      rpy="0 0 0" />
    <parent link="hitch_link" />
    <child link="chassibigga_uni" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-0.6"
      upper="0.6"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>

  <link name="chassibigga_uni">
    <inertial>
      <origin rpy="0 0 0" xyz="0.003381 1.5929e-07 0.02162" />
      <mass value="0.5" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
  </link>

  <joint name="eixochassibigga_cambao"
    type="revolute">
    <origin
      xyz="0 1.1578 0.0112477"
      rpy="0 0 0" />
    <parent link="chassibigga_uni" />
    <child link="cambao" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="-0.6"
      upper="0.6"
      effort="100"
      velocity="1" />
    <dynamics
      damping="0"
      friction="0" />
  </joint>

  <!-- Connector -->
  <link name="cambao">
    <inertial>
      <origin
        xyz="-0.0010213 -0.38489 0.0092469"
        rpy="0 0 0" />
      <mass
        value="1." />
      <inertia
        ixx="0.12"
        ixy="0.0"
        ixz="0.0"
        iyy="0.12"
        iyz="0.0"
        izz="0.12" />
    </inertial>
    <visual>
      <origin
        xyz="0 -0.7 0"
        rpy="0 0 0" />
     <geometry>
        <box size="0.1 1.2 0.08"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.64706 0.61961 0.58824 1" />
      </material>
    </visual>
  </link>

  <gazebo reference="cambao">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <joint name="eixocambao_chassi"
    type="revolute">
    <origin
      xyz="0 0.445 -0.31525"
      rpy="0 0 0" />
    <parent link="cambao" />
    <child link="chassi" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-0.4"
      upper="0.4"
      effort="100"
      velocity="1" />
    <dynamics
      damping="0"
      friction="0" />
  </joint>

  <!-- Trailer -->
  <link name="chassi">
    <inertial>
      <mass
        value="80.702" />
        <xacro:box_inertia m="80.702" w="1" d="1.2" h="0.12"/>
    </inertial>
    <visual>
      <origin
        xyz="0 0 0.35"
        rpy="0 0 0" />
     <geometry>
        <box size="1 1.2 0.12"/>
      </geometry>
      <material
        name="Cyan">
        <color
          rgba="0.64706 0.61961 0.58824 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0.43"
        rpy="0 0 0" />
      <geometry>
        <box size="1 1.2 0.12"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="chassi">
    <material>Gazebo/Orange</material>
  </gazebo>

  <link name="rodeirodiant1">
    <inertial>
      <origin
        xyz="-0.010304 0.018687 -0.067271"
        rpy="0 0 0" />
      <mass
        value="0.5" />
      <inertia
        ixx="0.11"
        ixy="0.0"
        ixz="0.0"
        iyy="0.11"
        iyz="0.0"
        izz="0.11" />
    </inertial>
    <!-- <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://glr_description/models/rodeirodiant1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.64706 0.61961 0.58824 1" />
      </material>
    </visual> -->
  </link>

  <gazebo reference="rodeirodiant1">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="rodeirodiant2">
    <material>Gazebo/Orange</material>
  </gazebo>

  <joint name="eixorodeirodiant1" type="revolute">
    <origin
      xyz="0.39 -0.445 0.36525"
      rpy="0 0 0" />
    <parent
      link="chassi" />
    <child
      link="rodeirodiant1" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-1"
      upper="1"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="10.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>

  <link name="rodadiant1">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2" />
      <xacro:sphere_inertia m="2" r="0.14260"/>
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="rodadiant1">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="rodadiant2">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="eixorodadiant1"
    type="continuous">
    <origin
      xyz="0.08 0 -0.22125"
      rpy="0 0 0" />
    <parent
      link="rodeirodiant1" />
    <child
      link="rodadiant1" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-1E+30"
      upper="1E+30"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="10.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>

  <link name="rodeirodiant2">
    <inertial>
      <origin
        xyz="0.010304 0.018687 -0.067271"
        rpy="0 0 0" />
      <mass
        value="0.5" />
      <inertia
        ixx="0.011"
        ixy="0.0"
        ixz="0.0"
        iyy="0.011"
        iyz="0.0"
        izz="0.11" />
    </inertial>
    <!-- <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://glr_description/models/rodeirodiant2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.64706 0.61961 0.58824 1" />
      </material>
    </visual> -->
  </link>

  <joint name="eixorodeirodiant2"
    type="revolute">
    <origin
      xyz="-0.39 -0.445 0.36525"
      rpy="0 0 0" />
    <parent
      link="chassi" />
    <child
      link="rodeirodiant2" />
    <axis
      xyz="0 0 1" />
    <!-- <limit
      lower="-1"
      upper="1"
      effort="100"
      velocity="1" /> -->
    <limit
      lower="-0.7"
      upper="0.7"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="1.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>

  <gazebo>
    <joint name='barradiant1_JOINT_1' type='revolute'>
      <parent>barradiant1</parent>
      <child>rodeirodiant1</child>
      <pose>-0.06 0.185 -0.027 0 -0 0</pose>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-1.79769e+308</lower>
          <upper>1.79769e+308</upper>
          <effort>0</effort>
          <velocity>0</velocity>
        </limit>
        <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
          <damping>0</damping>
          <friction>1.2</friction>
        </dynamics>
      </axis>
      <physics>
        <ode>
          <limit>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </limit>
          <suspension>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </suspension>
        </ode>
      </physics>
    </joint>

    <joint name='barradiant2_JOINT_2' type='revolute'>
      <parent>barradiant2</parent>
      <child>rodeirodiant2</child>
      <pose>0.06 0.185 -0.027 0 -0 0</pose>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-1.79769e+308</lower>
          <upper>1.79769e+308</upper>
          <effort>0</effort>
          <velocity>0</velocity>
        </limit>
        <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
          <damping>0</damping>
          <friction>1.2</friction>
        </dynamics>
      </axis>
      <physics>
        <ode>
          <limit>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </limit>
          <suspension>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </suspension>
        </ode>
      </physics>
    </joint>

    <joint name='barratras1_JOINT_3' type='revolute'>
      <parent>barratras1</parent>
      <child>rodeirotras1</child>
      <pose>-0.18 0 -0.08 0 -0 0</pose>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-1.79769e+308</lower>
          <upper>1.79769e+308</upper>
          <effort>0</effort>
          <velocity>0</velocity>
        </limit>
        <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
          <damping>0</damping>
          <friction>1.2</friction>
        </dynamics>
      </axis>
      <physics>
        <ode>
          <limit>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </limit>
          <suspension>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </suspension>
        </ode>
      </physics>
    </joint>

    <joint name='barratras2_JOINT_4' type='revolute'>
      <parent>barratras2</parent>
      <child>rodeirotras2</child>
      <pose>0.18 0 -0.08 0 -0 0</pose>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-1.79769e+308</lower>
          <upper>1.79769e+308</upper>
          <effort>0</effort>
          <velocity>0</velocity>
        </limit>
        <dynamics>
          <spring_reference>0</spring_reference>
          <spring_stiffness>0</spring_stiffness>
          <damping>0</damping>
          <friction>1.2</friction>
        </dynamics>
      </axis>
      <physics>
        <ode>
          <limit>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </limit>
          <suspension>
            <cfm>0</cfm>
            <erp>0.2</erp>
          </suspension>
        </ode>
      </physics>
    </joint>
  </gazebo>

  <link name="rodadiant2">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2" />
      <xacro:sphere_inertia m="2" r="0.14260"/>
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
    </collision>
  </link>

  <joint name="eixorodadiant2"
    type="continuous">
    <origin
      xyz="-0.08 0 -0.22125"
      rpy="0 0 0" />
    <parent
      link="rodeirodiant2" />
    <child
      link="rodadiant2" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-1E+30"
      upper="1E+30"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="10.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>

  <link name="rodeirotras1">
    <inertial>
      <origin
        xyz="-0.014075 -2.2041E-06 -0.076225"
        rpy="0 0 0" />
      <mass
        value="0.5" />
      <inertia
        ixx="0.11"
        ixy="0.0"
        ixz="0.0"
        iyy="0.11"
        iyz="0.0"
        izz="0.11" />
    </inertial>
    <!-- <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://glr_description/models/rodeirotras1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.64706 0.61961 0.58824 1" />
      </material>
    </visual> -->
  </link>

  <gazebo reference="rodeirotras1">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="rodeirotras2">
    <material>Gazebo/Orange</material>
  </gazebo>

  <joint name="eixorodeirotras1"
    type="revolute">
    <origin
      xyz="0.39 0.445 0.36525"
      rpy="0 0 0" />
    <parent
      link="chassi" />
    <child
      link="rodeirotras1" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-1"
      upper="1"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="10.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>

  <link name="rodatras1">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2" />
      <xacro:sphere_inertia m="2" r="0.14260"/>
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="rodatras1">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="rodatras2">
    <material>Gazebo/Black</material>
  </gazebo>

  <joint name="eixorodatras1"
    type="continuous">
    <origin
      xyz="0.080 0 -0.22125"
      rpy="0 0 0" />
    <parent
      link="rodeirotras1" />
    <child
      link="rodatras1" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-1E+30"
      upper="1E+30"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="10.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>
  
  <link name="rodeirotras2">
    <inertial>
      <origin
        xyz="0.014075 -2.2041E-06 -0.076225"
        rpy="0 0 0" />
      <mass
        value="0.5" />
      <inertia
        ixx="0.11"
        ixy="0.0"
        ixz="0.0"
        iyy="0.11"
        iyz="0.0"
        izz="0.11" />
    </inertial>
    <!-- <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://glr_description/models/rodeirotras2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.64706 0.61961 0.58824 1" />
      </material>
    </visual> -->
  </link>

  <joint name="eixorodeirotras2"
    type="revolute">
    <origin
      xyz="-0.39 0.445 0.36525"
      rpy="0 0 0" />
    <parent link="chassi" />
    <child link="rodeirotras2" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="-1"
      upper="1"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="10.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>

  <link name="rodatras2">
    <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="2" />
      <xacro:sphere_inertia m="2" r="0.14260"/>
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
      <material
        name="">
        <color
          rgba="0.29804 0.29804 0.29804 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 1.5708 0" />
      <geometry>
        <cylinder radius="0.14260" length="0.08"/>
      </geometry>
    </collision>
  </link>

  <joint name="eixorodatras2"
    type="continuous">
    <origin
      xyz="-0.080 0 -0.22125"
      rpy="0 0 0" />
    <parent link="rodeirotras2" />
    <child link="rodatras2" />
    <axis
      xyz="1 0 0" />
    <limit
      lower="-1E+30"
      upper="1E+30"
      effort="100"
      velocity="1" />
    <calibration
      rising="0"
      falling="0" />
    <dynamics
      damping="0"
      friction="10.0" />
    <safety_controller
      soft_upper="0"
      soft_lower="0"
      k_position="0"
      k_velocity="0" />
  </joint>


  <!-- Generic LiDAR -->
  <link name="lidar_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
      <material name="lidar_material">
        <color rgba="0.2 0.2 0.2 1"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.07"/>
      </geometry>
    </collision>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="chassibigga"/>
    <child link="lidar_link"/>
    <origin xyz="0 -0.25 0.155" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <material>Gazebo/DarkGrey</material>
    <sensor type="ray" name="lidar_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_lidar" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/glr_description</namespace>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>